### ISSUE TITLE
Eliminación de un alumno / profesor

### ISSUE THREAD

**Issue by castromaciel** [PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd#22]
## Proceso

1. Iniciar sesión
2. Intentar eliminar un alumno/profesor

## Resultado esperado

Al ser una aplicación CRUD, se espera poder eliminar algun alumno o profesar para validar el correcto manejo del metodo delete.

## Resultado actual

No hay ninguna opcion de eliminación

## Captura

<img width="1297" alt="image" src="https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/83432755/6dc5a2b8-8062-4a7e-9123-560974e8a21a">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by PabloZottola** [comment]
Buenos dias Leandro, agregado el boton de borrar alumnos.
![image](https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/58942759/7a8269b8-637a-4965-8ed0-6f7eca209f7c)
![image](https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/58942759/d1a3c5e8-ef9c-41fd-91fb-65cac0a17a12)

**Comment by PabloZottola** [comment]
en las imagen borre a Veronica Analia Diaz
