### ISSUE TITLE
Filtrar por alumnos

### ISSUE THREAD

**Issue by castromaciel** [PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd#23]
## Proceso

1. Iniciar sesión
2. Filtrar por alumnos

## Resultado esperado

Se espera que filtre en base a las coincidencias de nombre

## Resultado actual

Se ingresan dos letras coincidentes con el primer nombre y retorna "No se encontraron resultados"

## Captura

https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/83432755/e916d4fb-fa56-4dd6-9b61-69e68786814e

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by PabloZottola** [comment]
Buenos dias, ya esta implementado el debounce para que espere unos segundo hasta que recien haga las peticiones a la base de datos.
Tambien esto mejoro muchisimo el rendimiento por la cantidad de peticiones al back-end.

**Comment by PabloZottola** [comment]
![image](https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/58942759/706a4746-51d1-4f26-a9ef-3357c4bf4ed7)

**Comment by PabloZottola** [comment]
Buenos días Leandro, mi idea era que tuviera un filtro por cursado, ósea, si yo tipiaba por ejemplo el numero "1", me aparecían todos los alumnos de ese año.
Ya borre esas líneas de código y ahora se puede usar como vos me indicaste. Muchas gracias

**Comment by PabloZottola** [comment]
![image](https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/58942759/5f30749f-919e-435c-a8e6-a20b13ac7dc3)
