### ISSUE TITLE
Registro de alumno duplicado

### ISSUE THREAD

**Issue by castromaciel** [PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd#24]
## Proceso

1. Iniciar sesión (admin)
2. Registro de profesores
3. Registro de Alumnos

## Resultado esperado

Se esperaba que al registrar dos veces al mismo usuario saliera una alerta de que el usuario ya existe.

## Resultado actual

Al crear un nuevo usuario con los datos de un usuario existente se genera una alerta de "usuario creado".

## Captura

https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/83432755/2039f6ad-0d46-44f7-9dd3-925ad93d4a84

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by PabloZottola** [comment]
Buenos dias, el problema que surgia ahi es que no tenia un pantalla de loading cuando hacia la validacio en el back-end.
Ya esta solucionado.
Cree el state "isShowModalLoading", para que cuando haga las peticiones en el back-end.
![image](https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/58942759/0166ed77-fc08-44e0-9738-137616e90770)
![image](https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/58942759/dcbece37-1a74-4791-959e-6f9ed86f5b77)
