### ISSUE TITLE
Inicio de sesión

### ISSUE THREAD

**Issue by castromaciel** [PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd#25]
## Proceso

1. Iniciar sesión

## Resultado actual

Al intentar iniciar sesión, no hay un spinner de carga y permite dar click en login muchas veces.
Ocurre lo mismo con todos los botones que interactuan con el backend

## Captura

https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/83432755/558764e6-77fd-4649-a631-63d9848db7b3

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by PabloZottola** [comment]
Buenos dias Leandro, ya esta solucionado este problema, como vos decis con todas las peticiones a la base de datos se podia hacer infinitas peticiones hasta que responda la bd.
Lo solucione creando un state llamado loading, que cuando uno hace click en los botones, este activa el atributo "disable" en el buttom que ejecuta la peticion al bakc-end, y hasta que no cumpla con esa peticion no podes darle click nuevamente.

**Comment by PabloZottola** [comment]
![image](https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/58942759/bc9241f9-9180-45a8-83ee-f87f376775eb)
