### ISSUE TITLE
Eliminar console logs

### ISSUE THREAD

**Issue by castromaciel** [PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd#26]
Para una estructura de proyecto mucho más limpia, se recomienda eliminar todos los console.logs que son para el desarrollador.

https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/83432755/d2f9f349-b731-42b4-b855-4d1e361d408d

**Comment by PabloZottola** [comment]
Ya se eliminaron los console.log();

**Comment by castromaciel** [comment]
Quedan logs pendientes:

<img width="1287" alt="image" src="https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/83432755/e5b2c2d4-8ee9-4fb3-ae52-ceac0b8ed245">

Referencia:

https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/blob/012868140c631810ec18f0f4ce43275a3abb30c1/src/admin/components/ImputCreateStudents.jsx#L23-L30

**Comment by PabloZottola** [comment]
Buenos días, borrado ese console.log() 👍
