### ISSUE TITLE
Error en consola 'Cannot read properties of null'

### ISSUE THREAD

**Issue by castromaciel** [PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd#27]
## Proceso

1. Iniciar sesión
2. Dar click en el logo

## Resultado esperado

1. Se espera que al dar click en el logo me redirija al inicio

## Resultado actual

Si bien redirije, está dando un error no controlado en la consola

## Captura

https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/83432755/72ef35df-4ee3-4f19-a1e5-f9e25de25e3c

<img width="1436" alt="image" src="https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/83432755/28efe3ed-a426-461f-a763-b90679f0e71e">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by PabloZottola** [comment]
Buenos dias, este problema era por un funcion que tenia que cuando vos hacias click en el logo para ver los detalles del usuario logeado y hacias click fuera del popover se cerraba, por algun motivo donde vos toques despues de cerrar el modal seguia llamanda la funcion y ocacionaba ese error.
Para solucionarlo puse para que se cierre volviendo a hacer click en el logo.
