### ISSUE TITLE
Lista de profesores

### ISSUE THREAD

**Issue by castromaciel** [PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd#28]
## Proceso

1. Iniciar sesión
2. Administración

## Resultado esperado

Se esperaba que en la interfaz también exista una lista de profesores como la hay de alumnos.

## Resultado actual

Actualmente no se tiene una lista de los profesores, a pesar de que se consulta al servicio

## Captura

![image](https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/83432755/59044981-7a78-4608-94ff-32a11da29420)

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by PabloZottola** [comment]
Buenos dias Leandro, cree donde botones en la parte superior izquierda que haciendole click, muestra la lista de alumnos como la lista de profesores.
![Captura de pantalla 2024-01-10 114410](https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/58942759/1f7d7ad6-fdd9-43bb-bcf8-b4953772ea77)

**Comment by PabloZottola** [comment]
![image](https://github.com/PabloZottola/proyectoFinalRollingCodeSchoolFrontEnd/assets/58942759/0ab53190-5d96-4c1c-b2eb-370e1eb48544)
